### ISSUE TITLE
Promcat is not support postgres 13

### ISSUE THREAD

**Issue by micemuni** [sysdiglabs/promcat-resources#141]
Hi Team,
Can you please confirm that Promcat is not support postgresql 13 version as per the https://promcat.io/apps/postgresql

**Comment by daviddetorres** [comment]
Hi, 

We just tested the exporter and the dashboards with PostgreSQL v13 and they are fully compatible.

**Comment by micemuni** [comment]
@daviddetorres  Thanks for the update, when will it release to use..?

**Comment by daviddetorres** [comment]
Hi, 

The current resources (dashboards, alerts... etc.) are already compatible with Postgres 13. It was documented compatibility with v12 because still v13 was not tested. 

Did you have any problem with these resources with v13?
