### ISSUE TITLE
Access Forbidden

### ISSUE THREAD

**Issue by faezitrat** [sysdiglabs/promcat-resources#249]
Hello - while trying to run promcat.io, the following error is being generated. Can this be looked at?

* TLSv1.3  (IN), TLS handshake, [no content] (0):

* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):

* TLSv1.3 (IN), TLS app data, [no content] (0):

< HTTP/1.1 403 Forbidden

< Content-Type: text/plain; charset=utf-8

< X-Content-Type-Options: nosniff

< Date: Mon, 21 Nov 2022 20:32:25 GMT

< Content-Length: 12

<

Forbidden:

* Connection #0 to host localhost left intact

bash-4.4$

bash-4.4$

**Comment by daviddetorres** [comment]
Hi,

This repository contains only docs and resources. If you want to see them in a UI fashion, you can go to https://PromCat.io
